//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carniceria.DS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DS : global::System.Configuration.ApplicationSettingsBase {
        
        private static DS defaultInstance = ((DS)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DS())));
        
        public static DS Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-KG8RE07\\SQLEXPRESS;Initial Catalog=Carniceria;Integrated Secu" +
            "rity=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=Carniceria;Integrated Security=True")]
>>>>>>> cc8e1dfc8e75d2fad82b5f0024c019057423c6fc
        public string conexion {
            get {
                return ((string)(this["conexion"]));
            }
        }
    }
}
